# Generated by Django 3.1.3 on 2021-02-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0006_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='telefon',
            field=models.TextField(),
        ),
    ]
