# Generated by Django 3.1.3 on 2021-02-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0007_auto_20210217_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
