# Generated by Django 3.1.3 on 2021-02-19 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0009_auto_20210219_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='img',
        ),
    ]
